### ISSUE TITLE
Add GitHub Issue Template / Contributing?

### ISSUE THREAD

**Issue by bih** [bih/spotify-ruby#34]
GitHub supports `CONTRIBUTING.md` and `.github/ISSUE_TEMPLATE.md` for mentioning guidelines for contributing and a default description when creating a new issue.

We would benefit greatly from having a straightforward set of documents mentioning what we expect from community contributors, and recommendations on getting a PR approved, etc.

Any discussions relating to this can happen here too!

**Comment by viren140290** [comment]
@bih I'd like to take this one up if you don't mind.

**Comment by bih** [comment]
Marked as taken! Feel free to let me know if you've got any questions 🙂

**Comment by viren140290** [comment]
I see that you already have a contribution section in the README that points to a webpage. Do you just want to keep that and not add a separate CONTRIBUTION.md?
