### ISSUE TITLE
Migrate Changelog in README.md to docs/CHANGELOG.md

### ISSUE THREAD

**Issue by bih** [bih/spotify-ruby#49]
We need to move the `Changelog` section in `README.md` to `docs/CHANGELOG.md` so we can refer to it in the website and on GitHub too. We can have a reference to the file in the `README.md` too

**Comment by aminamos** [comment]
This section no longer exists, right?

**Comment by bih** [comment]
Oh interesting, I believe not. There hasn't been many updates since!
