### ISSUE TITLE
Authorization url outdated

### ISSUE THREAD

**Issue by johnro** [bih/spotify-ruby#66]
Hi team! Thanks for the great library, I'm using in a project now, and I noticed that the `@accounts.authorization_url` seems like its outdated. 

The url returned is `https://accounts.spotify.com/oauth/authorize?client_id=...` which gives an error when trying to access it.

`https://accounts.spotify.com/authorize?` seems to work. 

See #65 

Thanks!

**Comment by bih** [comment]
This is merged :)
